export enum ActionTypes {
  PRODUCT_SET = '[PRODUCT] PRODUCT_SET',
  PRODUCT_CLEAR = '[PRODUCT] PRODUCT_CLEAR',

  PRODUCTCATALOG_SET = '[PRODUCTCATALOG] PRODUCTCATALOG_SET',
  PRODUCTCATALOG_CLEAR = '[PRODUCTCATALOG] PRODUCTCATALOG_CLEAR',
}
