export enum ActionTypes {
  PRODUCT_SET = '[PRODUCT] PRODUCT_SET',
  PRODUCT_CLEAR = '[PRODUCT] PRODUCT_CLEAR',

  PRODUCTCATALOG_SET = '[PRODUCTCATALOG] PRODUCTCATALOG_SET',
  PRODUCTCATALOG_CLEAR = '[PRODUCTCATALOG] PRODUCTCATALOG_CLEAR',

  SHOPPINGCART_ADD = '[SHOPPINGCART] SHOPPINGCART_ADD',
  SHOPPINGCART_REMOVE = '[SHOPPINGCART] SHOPPINGCART_REMOVE',
  SHOPPINGCART_INCREMENT = '[SHOPPINGCART] SHOPPINGCART_INCREMENT',
  SHOPPINGCART_DECREMENT = '[SHOPPINGCART] SHOPPINGCART_DECREMENT'
}
